services:
  - type: web
    name: my-web-service
    env: node
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    envVars:
      - key: POSTGRESURL
        value: postgres://cascadepg_user:WReQeXFT8D9H0nrsyFplFCaC5Ru3Ieaw@dpg-cpi5ch21hbls73bcf5i0-a.oregon-postgres.render.com/cascadepg
